ALTER TABLE public.post ADD COLUMN post_type_id int4 NULL;
ALTER TABLE public.post ADD COLUMN accepted_answer_id int4 NULL;
ALTER TABLE public.post ADD COLUMN parent_id int4 NULL;
ALTER TABLE public.post ADD COLUMN score int4 NULL;
ALTER TABLE public.post ADD COLUMN view_count int4 NULL;
ALTER TABLE public.post ADD COLUMN body varchar (30) NULL;
ALTER TABLE public.post ADD COLUMN owner_user_id int4 NULL;
ALTER TABLE public.post ADD COLUMN owner_display_name varchar (30) NULL;
ALTER TABLE public.post ADD COLUMN tags varchar (30) NULL;
ALTER TABLE public.post ADD COLUMN answer_count int4 NULL;
ALTER TABLE public.post ADD COLUMN comment_count int4 NULL;
ALTER TABLE public.post ADD COLUMN favorite_count int4 NULL;
ALTER TABLE public.post ADD COLUMN closed_date date NULL;
ALTER TABLE public.post ADD COLUMN community_owner_date date NULL;